import { defineConfig } from 'tsup';

export default defineConfig([
  // Library build
  {
    entry: ['src/index.ts'],
    format: ['esm', 'cjs'],
    splitting: false,
    sourcemap: false,
    dts: true,
    clean: true,
    target: 'node18',
    outDir: 'dist',
    shims: true,
    minify: true,
    treeshake: true,
    platform: 'node',
    bundle: true,
    noExternal: [
      'svgfusion-core',
      'svgfusion-react',
      'svgfusion-vue',
      'svgfusion-utils',
      'svgfusion-cli',
      'svgfusion-browser',
    ],
    external: ['chalk', 'commander', 'jsdom', 'zod'],
  },
  // Browser build
  {
    entry: { browser: 'src/browser.ts' },
    format: ['esm'],
    splitting: false,
    sourcemap: false,
    dts: true,
    clean: false,
    target: 'es2020',
    outDir: 'dist',
    shims: true,
    minify: true,
    treeshake: true,
    platform: 'browser',
    bundle: true,
    noExternal: [
      'svgfusion-browser',
      'svgfusion-core/browser',
      'svgfusion-utils/browser',
    ],
    external: [
      'fs',
      'path',
      'fs/promises',
      'figlet',
      'chalk',
      'commander',
      'jsdom',
      'zod',
      'os',
      'util',
      'process',
      'assert',
      'v8',
      'module',
      'url',
    ],
    terserOptions: {
      output: {
        comments: false,
      },
    },
  },
  // CLI build (unminified to preserve shebang)
  {
    entry: { cli: 'src/cli.ts' },
    format: ['cjs'],
    splitting: false,
    sourcemap: false,
    dts: true,
    clean: false,
    target: 'node18',
    outDir: 'dist',
    shims: true,
    minify: false,
    treeshake: false,
    platform: 'node',
    bundle: true,
    noExternal: [
      'svgfusion-core',
      'svgfusion-react',
      'svgfusion-vue',
      'svgfusion-utils',
      'svgfusion-cli',
      'svgfusion-browser',
    ],
    external: ['chalk', 'commander', 'jsdom', 'zod', 'figlet'],
  },
]);
