name: Deploy PR to Netlify

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docs/**'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  deploy-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'docs/package-lock.json'
          
      - name: Install dependencies
        run: |
          cd docs
          npm ci
          
      - name: Build documentation
        run: |
          cd docs
          npm run build
          
      - name: Deploy PR to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './docs/build'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy PR #${{ github.event.number }} - ${{ github.event.pull_request.title }}"
          alias: "pr-${{ github.event.number }}--svgfusion"
          enable-pull-request-comment: true
          enable-commit-comment: false
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 2